### PR TITLE
more timezone conversion

### PR DESCRIPTION
**Pull request by ihackcode**

### CODE REVIEW

**Comment by mambax7** [comment]
Thank you!

**Comment by mambax7** [comment]
What is the "U" stand for in ItemForm.php? 
$dateexpire = formatTimestamp($dateexpire, 'U', $timeoffset);

**Comment by mambax7** [comment]
When I tried to change the exparation date on an existing article, I've got following errors:
Notice: Array to string conversion in file /class/libraries/vendor/xoops/xmf/src/FilterInput.php line 251
--
Error: Exception: DateTimeZone::__construct(): Unknown or bad timezone (0.0) in file /modules/publisher/class/Item.php line 1105

I'll take a look at that, but just wanted to let you know....

**Comment by ihackcode** [comment]
Its for Unix time.
https://www.php.net/manual/en/function.date.php 

U | Seconds since the Unix Epoch (January 1 1970 00:00:00 GMT)

**Comment by mambax7** [comment]
But in the function:
 public static function formatTimestamp($time, $format = 'l', $timeoffset = null)
we don't have "U" format, right? 

Or do I miss something? 

Normally it goes this way:

1) $dateexpire = formatTimestamp($dateexpire, 'U', $timeoffset);
2) return XoopsLocal::formatTimestamp($time, $format, $timeoffset);
3) public static function formatTimestamp($time, $format = 'l', $timeoffset = null)

But we don't have any option here for "U"

**Comment by mambax7** [comment]
Let me check if maybe I've made some changes locally that now conflict with your changes...

**Comment by ihackcode** [comment]
I see.I forgot that I had issues with DateTimeZone earlier with those timezones with decimals.

**Comment by mambax7** [comment]
Speaking of Unix format, I suggested to use ISO format - see my discussion with Richard:
https://github.com/XOOPS/XoopsCore25/issues/837

**Comment by ihackcode** [comment]
It's here that i'm able to use 'U'. https://github.com/XOOPS/XoopsCore25/blob/master/htdocs/class/xoopslocal.php#L213
for this PR I only needed to convert the dateexpire time that I get from the database to the user's local time and pass it to XoopsFormDateTime that handles the formatting for me. 

PR #136 with the item.php issue with the timezone conversion. I'll need to somehow convert the user's local time to GMT (to store in the database).

**Comment by ihackcode** [comment]
I'll look into this more on Sunday. I forgot about userTimeToServerTime.

**Pull request merged**
