### PR TITLE
fix bugs uploading category image

### PR DESCRIPTION
**Pull request by ggoffy**
missing upload directory for category images:
uploads/publisher/images/category/
changed include/onupdate.php

error when uploading category image
admin/category.php:
REM line 85
line 86: replaced [quote] if (!is_readable($tmp_name) || !($tmp_name =
$temp3['tmp_name'])) {[/quote] by [quote]if
(!is_readable($temp['tmp_name']) || ($temp['tmp_name'] == '')) {[/quote]

### CODE REVIEW

**Comment by mambax7** [comment]
Thanks for the submissions. I've included your fix for the image upload. 
For the folders, I did a little bit differently, in order to be consistent with the oninstall routine. 
Can you check if it works for you? 
If you have improvement suggestions for it, I am totally open.

**Comment by ggoffy** [comment]
looks nice and do the same :-)

additional question: shouldn't there be an 'images/item' folder?

**Comment by mambax7** [comment]
Not really, since Publisher is using the ImageManager, i.e. the images are being managed "centrally" by XOOPS. This is a good thing, because in the ImageManager you can see all images from XOOPS as well as from Publisher, all in one place. 
But we need to create a better solution for 2.6.0, where all modules could use it in the same consistent way. It would be a "MediaManager" that would manage images, video, and audio files, with a nice taxonomy of the files.

**Comment by ggoffy** [comment]
sounds good

**Pull request merged**
