### PR TITLE
update publisher

### PR DESCRIPTION
**Pull request by liomj**
- added Option to display default image if no article image selected in article page 
- separate Latest Published Article in Index/Category and Article Page 
- changed Preferences order and add new option for better readibility 
 --Latest Published Articles in Index and Category Page
 --Article page
 --All Latest Published Articles in Article Page
 --Archive Page
 --Item by The Same Author Page
- added new options to enabled/disable item in article page
- added new options to enabled/disable item in item by the same author page 
- added new options to enabled/disable item in blocks 
 -- Random Block
 -- Latest News Block
 -- Spotlight Block
 -- Recent Block
 -- Column Block
 -- New Block
- restructured blocks and article templates
- restructured Latest Published Article templates
- added new options in preferences to enable/disable item in archive page
- restructured Archive page templates
- restructured Item by the same Author page templates
- separate Poster and Date in index,article page & blocks
- separate PDF and Print Button from AdminLinks
- removed unused tellafriend module support from AdminLinks
- removed unused Poster avatar from article page
- changed date format to 12 Hour format as default
- change XOOPS logo.gif to logo.png as default
- changed file.gif to transparent file.png in article page
- fixed Extended Column Block
- removed unused Topic Link (News Module) from Latest News Block
- added Default Article Image in PDF
- change TCPDF Logo to Blank.png in PDF Page
- change Text Header color from Blue to Black in PDF Page
- added PDF Protection in PDF Page
- added site name and slogan in Print Page
- fixed Default Template Breadcrumb
- fixed Category Image in Spotlight block
- fixed Footer that will be displayed at the index page of the module

### CODE REVIEW

**Comment by mambax7** [comment]
Thanks! I'll test it...

**Comment by liomj** [comment]
i have also updated the bootstrap publisher template for xbootstrap,xswatch and xswatch4

https://github.com/liomj/XoopsCore25/commit/c87970632d72e1d4fd10aceec68cbdbff231cd92

**Comment by mambax7** [comment]
Did you submit the bootstrap publisher templates to https://github.com/XOOPS/XoopsCore25/ ?

**Comment by liomj** [comment]
Not yet..Ill wait for my change to publisher to be approve first

**Comment by liomj** [comment]
Mamba Any chance to have this pull request to be approve

**Comment by mambax7** [comment]
So sorry for the delay! I'll try to review it by this weekend!!!!

**Comment by mambax7** [comment]
Thank you!!!

**Pull request merged**
