### PR TITLE
fixed bug (missing column) when saving article

### PR DESCRIPTION
**Pull request by ggoffy**

### CODE REVIEW

**Comment by mambax7** [comment]
Can you merge first the changes from the XOOPS Publisher 1.08 Alpha 3 as a pull, so we don't lose all the changes there? 
If you look at the network diagram, all these changes in there would not be visible in there anymore:
https://github.com/XoopsModules25x/publisher/network

**Comment by ggoffy** [comment]
I took the last code from here (2c0aaee)

**Comment by mambax7** [comment]
You took the  code, but not the "git version control", i.e. the code is OK, but we don't have the version control there

**Comment by mambax7** [comment]
You need to first "pull" from https://github.com/XoopsModules25x/publisher/, then apply your changes, and then issue a "Pull Request"

**Comment by ggoffy** [comment]
sorry, I do not know how. If I go to my branch and I create a new pull request it automatically creates always one from my branch to xoopsmodules25 and I do not know how to change direction

**Comment by mambax7** [comment]
Git Pull is different from a "pull request" 
See more info here: https://www.atlassian.com/git/tutorials/syncing/git-pull

Do you use GitTortoise or SourceTree or just Bash?

**Comment by ggoffy** [comment]
SourceTree

**Comment by mambax7** [comment]
1) Make sure that you have Upstream set as a remote:
image

2) Pull from Upstream (right click on "upstream"):
image

3) Pull the upstream "master" into your local "master" (right click on the "upstream master")
image


If there are conflicts, then fix them, then make your changes, then commit them to your Github location, and then issue a Pull Request

**Comment by ggoffy** [comment]
grafik
done.
and now?

**Comment by mambax7** [comment]
Now commit and push in SourceTree, then go to your Publisher location and issue a Pull Request. 
Actually, because you have one open here, then it will be probably included automatically here, so check here after you push in SounceTree

**Comment by mambax7** [comment]
OK, it looks like it is here :)

**Comment by mambax7** [comment]
So in the future, before starting work on something, and committing,  it is always good to first pull all the latest changes from Upstream, but also check in the Network:
https://github.com/XoopsModules25x/publisher/network
if there are any other newer updates from other people, so we can avoid potential conflicts, but also duplication of efforts and reinventing the wheel :)

**Pull request merged**
