### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by ihackcode**

### CODE REVIEW

**Comment by geekwright** [comment]
XOOPS depends on relative positions to reach files in its hierarchy. Using __DIR__ as the start of the position in that hierarchy is the norm, a building block we depend on.

With that said, I am a bit concerned with the changes that replace the __DIR__ relative constructs with $_SERVER['SCRIPT_FILENAME'] relative ones.  That will break on some systems which work fine in the current scheme.

Can you elaborate what your symlink issues are:
- What is XOOPS_ROOT_PATH?
- In the context of admin/admin_header.php, what is __DIR__ and what is $_SERVER['SCRIPT_FILENAME']?
- What is the  environment, OS, web server, PHP and SAPI?
- What is symlinked to where?

I am trying to understand the issue you are seeing, as the proposed solution seems to imply it should be systemic and widespread. Thanks for any assistance you can offer in that.

**Comment by ihackcode** [comment]
"Changes to make my symlinks work", was just something temporary to make the files work with my setup. It's not really a good solution. I just can't seem to find a variable/constant that would solve my issue. 

http://php.net/manual/en/language.constants.predefined.php
__FILE__	The full path and filename of the file with symlinks resolved. If used inside an include, the name of the included file is returned.
__DIR__	The directory of the file. If used inside an include, the directory of the included file is returned. This is equivalent to dirname(__FILE__). This directory name does not have a trailing slash unless it is the root directory.

__DIR__ is equivalent to dirname(__FILE__), So I guess the symlinks will always be resolved and I shouldn't use either __FILE__ or __DIR__ to get my path.
------------------

define('XOOPS_ROOT_PATH', 'C:/wamp64/www/x_/htdocs');

OS: Windows 8.1 Pro (64bit)
WAMP Server (64 bit) : Apache 2.4.17 , PHP 5.6.16 

- What is symlinked to where?
C:/wamp64/www/x_/htdocs/modules/publisher target is C:\Projects\GitHub\ihackcode\publisher .  __DIR__ is resolving the symlinks and trying to include mainfile.php in the GitHub folder instead of htdocs .

**Comment by geekwright** [comment]
OK, that makes sense why you are having an issue.

When we were setting up modules on GitHub, I pushed to make the top level the actual module directory, not just a container with a module directory inside. You'll still see related commit comments "move everything up a level" or something similar. That was so that you can clone a module repo directly into the modules directory in a XOOPS installation, and then work on it there. I do it that way all the time, and no symlink is needed. Git works fine in the cloned directory, and the git operations in the main XOOPS directories just mention the directory as being there, and don't list every file as untracked.

I will disclose that I live in Linux most of the time, but I have used this technique on Windows with the official GitHub client. It defaults to its own directory, but it will manage repositories anywhere with just a little push.

A workflow based on that technique might make your life a little bit easier.

We do want to make sure your "temporary" changes don't get committed, as that solution really can create new issues in some environments.

**Comment by ihackcode** [comment]
Thanks. I'll do that.

**Pull request closed without merging**
