### PR TITLE
updates

### PR DESCRIPTION
**Pull request by mambax7**

### CODE REVIEW

**Comment by ihackcode** [comment]
I had to add #167 to fix that issue with TPL, but I noticed a different issue.

I'm having issues with the blocksadmin when i'm saving changes to blocks like the Alignment or Cache lifetime I get the error below.

( ! ) Fatal error: Cannot declare class XoopsBlock, because the name is already in use in C:\wamp64\www\XoopsCore25_latest\htdocs\kernel\block.php on line 0

**Comment by mambax7** [comment]
Which XOOPS version are you using?

**Comment by mambax7** [comment]
@ihackcode, I hope, the latest commit fixes that:
https://github.com/XoopsModules25x/publisher/pull/166/commits/223e412ddd5dd555a0e17dce91e7b22b06836a62
Please test it and let me know...

**Comment by ihackcode** [comment]
I was able to look at it again today. It looks like the blocksadmin is using both class/xoopsblocks.php and kernel/blocks.php (xoopsblocks) (from xoops_getHandler('block')). I think it should be updated to use the one from kernel. I'll try to update it today.

**Comment by mambax7** [comment]
@ihackcode No, we should use the class/xoopsblocks.php. It was my mistake that I switched to kernel/xoopsblocks.php
It was my mistake that I switched to  kernel/xoopsblocks.php and the https://github.com/XoopsModules25x/publisher/commit/223e412ddd5dd555a0e17dce91e7b22b06836a62 fixed that.

**Comment by ihackcode** [comment]
ah okay, we should be using the one from class/xoopsblocks.php.  

I have the latest, but the xoops_getHandler('block') will try to load the one from kernel.

**Comment by mambax7** [comment]
Let me look into it. How can I replicate it? When is it happening? Is it still the same as before:

> "when i'm saving changes to blocks like the Alignment or Cache lifetime I get the error below."

**Comment by ihackcode** [comment]
It's in the blocksadmin in publisher when I set the alignment or cache lifetime of a blocks. 
capture33

I think its because of the change from https://github.com/mambax7/publisher/commit/b6f523eaff40d606327d8a31d1b0c7bf134d66bb#diff-20e438de891abdd05b9d32744aaee241268978bfacf2f56ab2df9fdf0001770eL436
$myblock->store(); was removed and replaced with the block handler.

**Comment by mambax7** [comment]
@ihackcode BTW - do you use the latest [XOOPS 2.5.11](https://github.com/XOOPS/XoopsCore25/)?

**Comment by ihackcode** [comment]
I have XOOPS 2.5.10

**Comment by mambax7** [comment]
Can you try 2.5.11?

**Comment by mambax7** [comment]
Can you also change locally to the `$myblock->store();`  and see if it makes a difference?

**Comment by mambax7** [comment]
@ihackcode I just tested on 2.5.10: when you reverse back to `$myblock->store();` then it works: 
```php
        $myblock->store();
//        /** @var \XoopsBlockHandler $blockHandler */
//        $blockHandler = xoops_getHandler('block');
//        return $blockHandler->insert($myblock);
```

**Comment by ihackcode** [comment]
> @ihackcode I just tested on 2.5.10: when you reverse back to `$myblock->store();` then it works:
> 
> ```
> $myblock->store();
> //        /** @var \XoopsBlockHandler $blockHandler */
> //        $blockHandler = xoops_getHandler('block');
> //        return $blockHandler->insert($myblock);
> ```

That's what I'm also seeing on 2.5.10 and 2.5.11 Beta 1, when I revert the two locations that is using that block handler.

I'm using PHP 7.3.30

**Comment by mambax7** [comment]
I just reverted it: https://github.com/XoopsModules25x/publisher/pull/166/commits/fea27b069bee11524d7f3fd73ee12047b8351e99

**Comment by mambax7** [comment]
Thanks for reporting the issue - if you see something else, please let me know

**Comment by ihackcode** [comment]
Looking good so far

**Pull request merged**
